$(document).ready(
    function(){
        let flaga=false
        $(".przycisk").click(
            function(){
                $("#big_godlo").fadeOut(200)
                $(".ob2").delay(200).animate({"opacity":"1"},200);
            }
        )
        $(".pa").click(
            function(){
                    $("#tlo").fadeIn(500).animate({"width":"100vw","height":"100vh","left":"0%","top":"0%","border-radius":"0"},1000);
                    $(".flaga").delay(1500).fadeIn(200).animate({"opacity":"1","width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000);
                    $("#gp").delay(1500).fadeIn(0).animate({"left":"85vw"},0).animate({"opacity":"1"},1000);
                    $("#wroc").delay(1500).animate({"top":"92.5vh"},1000);
                    flaga=true
                    }
                );
        $(".pb").click(
            function(){
                $("#tlo").fadeIn(500).animate({"width":"100vw","height":"100vh","left":"0%","top":"0%","border-radius":"0"},1000);
                $(".godlo").delay(1500).fadeIn(200).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px","opacity":"1"},1000);
                $("#fp").delay(1500).fadeIn(0).animate({"left":"5vw"},0).animate({"opacity":"1"},1000);    
                $("#kp").delay(1500).fadeIn(0).animate({"right":"5vw"},0).animate({"opacity":"1"},1000);
                $("#wroc").delay(1500).animate({"top":"92.5vh"},1000);
                flaga=false
            }
        );
        $(".pc").click(
            function(){
                $("#tlo").fadeIn(500).animate({"width":"100vw","height":"100vh","left":"0%","top":"0%","border-radius":"0"},1000);
                $(".kon").delay(1500).fadeIn(200).animate({"opacity":"1"},200).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000);
                $("#gp").delay(1500).fadeIn(0).animate({"left":"5vw"},0).animate({"opacity":"1"},1000);
                $("#wroc").delay(1500).animate({"top":"92.5vh"},1000);
                flaga=false
            }
        );
        $("#fp").click(
            function(){
                $("#fp,#kp").fadeOut(200);
                $("#gp").fadeIn(0).animate({"left":"85vw","top":"120vh","opacity":"1"},0).animate({"top":"80vh"},1000)
                $(".godlo").fadeIn(0).animate({"left":"160vw","opacity":"0","width":"10vw","height":"10vh"},1000).animate({"left":"50%","margin-left":"-5vw","top":"50%"},0)
                $(".flaga").fadeIn(0).animate({"left":"-30vw","opacity":"1"},0).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000)
                flaga=true
            }
        );
        $("#gp").click(
            function(){
                $("#gp").fadeOut(200);
                $("#kp").animate({"right":"5vw"},0)
                $("#fp").animate({"left":"5vw"},0)
                $("#fp,#kp").animate({"top":"120vh","opacity":"1"},0).fadeIn(0).animate({"top":"80vh"},1000)
            if (flaga==true){
                $(".flaga").fadeIn(0).animate({"left":"-60vw","opacity":"0","width":"10vw","height":"10vh"},1000).animate({"left":"50%","margin-left":"-5vw","top":"50%"},0)
                $(".godlo").fadeIn(0).animate({"left":"130vw","opacity":"1"},0).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000)
                flaga=false}
            else{
                $("#tajne").fadeOut(200)
                $(".kon").fadeIn(0).animate({"left":"160vw","opacity":"0","width":"10vw","height":"10vh"},1000).animate({"left":"50%","margin-left":"-5vw","top":"50%"},0)
                $(".godlo").fadeIn(0).animate({"left":"-30vw","opacity":"1"},0).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000)
            }
            }
        );
        $("#kp").click(
            function(){
                $("#fp,#kp").fadeOut(200);
                $("#gp").fadeIn(0).animate({"left":"5vw","top":"120vh","opacity":"1"},0).animate({"top":"80vh"},1000)
                $(".godlo").animate({"left":"-60vw","opacity":"0","width":"10vw","height":"10vh"},1000).animate({"left":"50%","margin-left":"-5vw","top":"50%"},0)
                $(".kon").fadeIn(0).animate({"left":"130vw","opacity":"1"},0).animate({"width":"50vw","height":"80vh","left":"25vw","top":"10vh","margin":"0px"},1000)
                flaga=false
                $("#tajne").fadeIn(200);
            }
        );
        $("#wroc").click(
            function(){
                $(".tekst").animate({"width":"10vw","height":"10vh","left":"50%","top":"40vh","margin-left":"-5vw"},1000).fadeOut(200);
                $("#tlo").delay(1000).animate({"width":"5vw","height":"5vh","left":"45vw","top":"45vh","border-radius":"15px"},1000).fadeOut(200);
                $("#gp,#fp,#kp").animate({"opacity":"0"},1200).fadeOut(0); 
                $("#wroc").animate({"top":"110vh"},1200)
                $("#tajne").fadeOut(200)
          }
        );
             //INNE
        $(".ob2").click(
            function(){
                    $(".ob2").animate({"opacity":"0"},500);
                    $("#big_godlo").fadeIn(500);
            }
        );
        $("#big_godlo").click(
            function(){
                    $("#big_godlo").fadeOut(500);
                    $(".ob2").animate({"opacity":"1"},500);
            }
        );
        $(".ob3").click(
            function(){
                $(".ob3").animate({"opacity":"0"},500);
                $("#big_polska").fadeIn(500);
                $("#polski_key").animate({"opacity":"1"},500);
            }
        );
        $("#polski_key").click(
            function(){
                if(tekst==true){
                $(".ob3").delay(500).animate({"opacity":"1"},500);
                $("#tlo_woj").animate({"right":"-50vw"},500)
                $("#big_polska").animate({"left":"50%","margin-left":"-26vh"},500).fadeOut(500);
                $("#polski_key").animate({"left":"50%","margin-left":"-5vw"},500).animate({"opacity":"0"},500);
                $(".tresc").delay(500).fadeOut(0);
                $("#woj_ramka").delay(500).fadeOut(0);
                tekst=false}
                else{
                    $(".ob3").animate({"opacity":"1"},500);
                    $("#big_polska").fadeOut(500);
                    $("#polski_key").animate({"opacity":"0"},500);
                }
            }
        );


        //województwa
        let tekst=false
        $("#zachodnio_pomorskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w1").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w1").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#pomorskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w2").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w2").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#warminsko_mazurskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w3").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w3").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#podlaskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w4").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w4").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#lubelskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w5").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w5").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#podkarpackie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w6").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w6").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#malopolskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w7").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w7").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#slaskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w8").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w8").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#opolskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w9").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w9").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#dolnoslaskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w10").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w10").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#lubuskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w11").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w11").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#wielkopolskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w12").fadeIn(0);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w12").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#kujawsko_pomorskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w13").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w13").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#mazowieckie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w14").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w14").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#lodzkie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w15").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w15").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        $("#swietokrzyskie").click(
            function(){
                if(tekst==false){
                    $("#woj_ramka").fadeIn(0);
                    $("#tlo_woj").fadeIn(0).animate({"right":"0vw"},500);
                    $(".w16").fadeIn(0);
                    $("#big_polska").animate({"left":"15%","margin-left":"0"},500);
                    $("#polski_key").animate({"left":"25%","margin-left":"0"},500)
                    tekst=true}
                else{
                    $("#tlo_woj").animate({"right":"-50vw"},500);
                    $(".tresc").delay(500).fadeOut(0);
                    $(".w16").delay(500).fadeIn(0);
                    $("#tlo_woj").delay(500).animate({"right":"0vw"},500);
                }
            }
        );
        
    }
);